name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_AUTHOR: ${{ secrets.GIT_AUTHOR }}
      GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
      HUSKY: false
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: Resolve husky issue
        run: chmod ug+x .husky/*

      - name: Run EsLint, Prettier and Unit Tests
        run: npm test

      - name: Generate Code Coverage and Send Reports with Codecov
        run: npm run cov:send

      - name: Show Code Coverage in Console
        run: npm run cov:check

      - name: Build package
        run: yarn build

      - name: Authenticate with registry
        run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}

      - name: Set package as public
        run: npm config set access public

      - name: Set git config ability to create commits
        run: |
          git config user.name "${GIT_AUTHOR}"
          git config user.email "${GIT_AUTHOR_EMAIL}"

      - name: Add GitHub to known_hosts
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Publish package
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run doc:html
          npm run doc:publish
          npm run release -- --ci --no-git.requireCleanWorkingDir
